### ISSUE TITLE
dyn pts not connected to sas factor seem to freeze the solve

### ISSUE THREAD

**Issue by mc2922** [JuliaRobotics/Caesar.jl#370] opened 2019-07-13 00:25 UTC
Ref example script : [examples/marine/asv/kayaks/testDynPtExFail.jl](https://github.com/JuliaRobotics/Caesar.jl/blob/b687818e922237d0fac099547d24ac51604aaae7/examples/marine/asv/kayaks/testDynPtExFail.jl#L1)

For size of 1 or 2 cliqs: solve completes, e.g. 
![image](https://user-images.githubusercontent.com/11624503/61164404-a7ac9d00-a4c9-11e9-818e-6fd62ec49fe5.png)
-> this is with (3) dyn pts ahead of the sas factor in the fg
-> in the script, use the following variables from line 18-20
windowlen = 8; #total variables in fg
saswindow = 5; #size of sas factor
sasstart = 4; #starting id of sas factor

For size of 3+ cliqs, solve freezes (for me at state machine iter 100):
![image](https://user-images.githubusercontent.com/11624503/61164422-cd39a680-a4c9-11e9-8535-4c4ecef1ac72.png)
-> this is with (4) dyn pts ahead of the sas factor in the fg
-> lines 18-20
windowlen = 9;
saswindow = 5;
sasstart = 5;

**Comment by dehann** [comment] 2019-07-14 00:31
There is definitely a bug in tree autoinit solve (as with this case) when there are sibling cliques.  The issue is that CSM is too eagerly blocking both siblings for different reasons.  After :x1 clique finishes (as indicated here) then :x7 should unblock in the priority order and complete it's upsolve.  Green means trying to initialize numerical values.  I'm working on this right now.

**Comment by dehann** [comment] 2019-07-14 01:27
Solver should be (but clearly isn't) following the progression described in JuliaRobotics/IncrementalInference.jl#344

**Comment by dehann** [comment] 2019-07-14 05:03
![Screenshot from 2019-07-14 01-02-30](https://user-images.githubusercontent.com/6412556/61179579-25a89b00-a5d3-11e9-9cd1-74d518be53b5.png)

**Comment by dehann** [comment] 2019-07-14 05:25
No, there is a deeper issue here.  This example shows it quite well actually:  The two siblings have now common separator variables.  The current CSM code assumed there would be, which is was a mistake.  

The solution is that the factors in the parent clique must also be used (where possible) to transfer information between siblings during the initialization process.  This makes total sense but I didn't see it that way before.

What I initially though was the issue is still an issue, but this example shows a second issue.  When transferring info from upsolved clique (:x1)'s :x3 variable to the right hand clique must use the :x3x4f1 odometry factor in the parent for a valid intersect with clique (:x7)'s separators.

**Comment by dehann** [comment] 2019-07-14 14:39
This other example shows the (what I initially thought) issue where (:x2) should solve first and then (:x4).  This example does not require parent factors to be used where transferring between siblings.

![Screenshot from 2019-07-12 19-05-15](https://user-images.githubusercontent.com/6412556/61185116-66c89b80-a623-11e9-80a6-43fbfa009c4a.png)

**Comment by dehann** [comment] 2019-07-14 15:28
Another example with connections between odometry chain on `:x*` and  `ls(fg, :l1) = Symbol[:x6l1f1, :x0l1f1]`, and one prior: `lsfPriors(fg) = Symbol[:x0f1]`
![Screenshot from 2019-07-14 11-26-10](https://user-images.githubusercontent.com/6412556/61185695-3b957a80-a62a-11e9-9925-d8a9f3023881.png)

**Comment by mc2922** [comment] 2019-08-02 09:09
Update on this: adding two factors freezes the solve at this point: 
![image](https://user-images.githubusercontent.com/11624503/62358924-9bb16b00-b4ca-11e9-9c5c-95611f96e814.png)

**Comment by mc2922** [comment] 2019-08-02 09:11
factor graph for two factors within an odo chain: 
![image](https://user-images.githubusercontent.com/11624503/62358971-b683df80-b4ca-11e9-9ed0-600d4d0de4ee.png)

please see example code here 
https://github.com/JuliaRobotics/Caesar.jl/blob/dynSAS/examples/marine/asv/kayaks/testDynPt2factors.jl

**Comment by mc2922** [comment] 2019-08-03 01:57
Resolved by increasing the solver limit
getSolverParams(fg).limititers=200

![image](https://user-images.githubusercontent.com/11624503/62405829-6141df80-b557-11e9-9d95-769a7411be81.png)

**Comment by dehann** [comment] 2019-08-03 02:04
great thanks

**Comment by dehann** [comment] 2019-08-03 02:05
also requires the parent sharing upgrade to the CSM code (used in the previous figure).

**Comment by dehann** [comment] 2019-08-22 03:32
original issue resolved but more working on tree based initialization required.

**Closed by dehann** 2019-08-22 03:32 UTC
Labels: autoinit, bug, clique state machine, inference
